# Generated by Django 3.1 on 2020-09-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='default.png', max_length=300, null=True, upload_to='pictures/'),
        ),
    ]
